export type Area = {
  slug: string;
  name: string;
  group: "cairo" | "giza" | "new-cities";
  isVip?: boolean;
  metaTitle: string;
  metaDescription: string;
  description?: string;
  compounds?: string[];
  neighborhoods?: string[];
};

export const areas: Area[] = [
  // ========== القاهرة ==========
  {
    slug: "nasr-city",
    name: "مدينة نصر",
    group: "cairo",
    metaTitle: "نقل أثاث مدينة نصر | شركة البركة - فرق متخصصة",
    metaDescription: "شركة البركة لنقل الأثاث في مدينة نصر. خدمة احترافية في جميع أحياء مدينة نصر، فك وتركيب وتغليف وونش رفع.",
    description: "نخدم جميع أحياء مدينة نصر بفرق متخصصة وسيارات مجهزة.",
    neighborhoods: ["الحي السابع", "الحي العاشر", "الحي الثامن", "المنطقة العاشرة", "عباس العقاد", "مكرم عبيد", "طيبة"],
  },
  {
    slug: "heliopolis",
    name: "مصر الجديدة",
    group: "cairo",
    metaTitle: "نقل أثاث مصر الجديدة | شركة البركة - خدمة راقية",
    metaDescription: "شركة البركة لنقل الأثاث في مصر الجديدة وهليوبوليس. خبرة في الفلل والشقق الفاخرة، تغليف احترافي وضمان كامل.",
    description: "متخصصون في نقل الأثاث الفاخر في مصر الجديدة وهليوبوليس.",
    neighborhoods: ["روكسي", "ميدان التحرير", "الوايلي", "الأمريكان", "كلية البنات", "قبة الهواء"],
  },
  {
    slug: "maadi",
    name: "المعادي",
    group: "cairo",
    metaTitle: "نقل أثاث المعادي | شركة البركة - خبراء المنطقة",
    metaDescription: "شركة البركة لنقل الأثاث في المعادي. متخصصون في فلل وشقق المعادي، خدمة VIP للأثاث الفاخر وضمان كامل.",
    description: "خبرة واسعة في نقل الأثاث الفاخر في المعادي وكورنيش المعادي.",
    neighborhoods: ["المعادي الجديدة", "دجلة", "المعادي القديمة", "كورنيش المعادي", "ثروت", "سكة الحديد"],
  },
  {
    slug: "zamalek",
    name: "الزمالك",
    group: "cairo",
    metaTitle: "نقل أثاث الزمالك | شركة البركة - خدمة فاخرة",
    metaDescription: "شركة البركة لنقل الأثاث في الزمالك. متخصصون في الشقق والفلل الفاخرة، خبرة في الأثاث الأنتيك والقيم.",
    description: "خبرة في نقل الأثاث الفاخر والأنتيك في أرقى أحياء القاهرة.",
    neighborhoods: ["شارع 26 يوليو", "حسن صبري", "إسماعيل محمد", "جزيرة الزمالك"],
  },
  {
    slug: "abbasia",
    name: "العباسية",
    group: "cairo",
    metaTitle: "نقل أثاث العباسية | شركة البركة - مقرنا الرئيسي",
    metaDescription: "شركة البركة مقرها في العباسية ميدان الجيش. أقرب شركة نقل أثاث لمنطقة العباسية والمناطق المجاورة.",
    description: "مقرنا الرئيسي في العباسية، نعرف المنطقة جيداً ونخدمها بأعلى كفاءة.",
    neighborhoods: ["ميدان الجيش", "الوايلي", "الأمير", "كوبري القبة", "الدراسة"],
  },
  {
    slug: "shubra",
    name: "شبرا",
    group: "cairo",
    metaTitle: "نقل أثاث شبرا | شركة البركة - خدمة سريعة",
    metaDescription: "شركة البركة لنقل الأثاث في شبرا. خدمة سريعة واحترافية في جميع أحياء شبرا بأسعار مناسبة.",
    description: "خدمة نقل أثاث سريعة واحترافية في جميع أحياء شبرا.",
    neighborhoods: ["شبرا مصر", "شبرا الخيمة", "روض الفرج", "الخليفة الأول"],
  },
  {
    slug: "ain-shams",
    name: "عين شمس",
    group: "cairo",
    metaTitle: "نقل أثاث عين شمس | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في عين شمس والمطرية. فرق مدربة وأسعار منافسة.",
    description: "نقل أثاث احترافي في عين شمس وما حولها.",
    neighborhoods: ["عين شمس الغربية", "عين شمس الشرقية", "المطرية", "المرج"],
  },
  {
    slug: "moqattam",
    name: "المقطم",
    group: "cairo",
    metaTitle: "نقل أثاث المقطم | شركة البركة - ونش وسيارات مجهزة",
    metaDescription: "شركة البركة لنقل الأثاث في المقطم. متخصصون في الونش ورفع الأثاث للأدوار العالية في المقطم.",
    description: "متخصصون في ونش الأثاث للأدوار العالية في المقطم.",
    neighborhoods: ["المقطم الأول", "المقطم الثاني", "المقطم الثالث", "الهضبة العليا"],
  },
  {
    slug: "katameya",
    name: "قطامية",
    group: "cairo",
    isVip: true,
    metaTitle: "نقل أثاث قطامية | شركة البركة - خدمة VIP للكمبوندات",
    metaDescription: "شركة البركة لنقل الأثاث في قطامية. متخصصون في كمبوندات قطامية الفاخرة وهايتس وهايد بارك.",
    description: "متخصصون في خدمة كمبوندات قطامية الفاخرة.",
    neighborhoods: ["قطامية هايتس", "قطامية الأشجار"],
    compounds: ["Hyde Park", "Katameya Heights", "Katameya Dunes", "Mountain View Katameya"],
  },

  // ========== الجيزة ==========
  {
    slug: "faisal",
    name: "فيصل",
    group: "giza",
    metaTitle: "نقل أثاث فيصل | شركة البركة - خدمة سريعة ومحترفة",
    metaDescription: "شركة البركة لنقل الأثاث في فيصل. خدمة سريعة في جميع شوارع فيصل بأسعار مناسبة وفرق مدربة.",
    description: "نقل أثاث احترافي في جميع شوارع وأحياء فيصل.",
    neighborhoods: ["شارع فيصل الرئيسي", "الهرم", "فيصل الأول", "الطالبية", "أبو النمرس"],
  },
  {
    slug: "haram",
    name: "الهرم",
    group: "giza",
    metaTitle: "نقل أثاث الهرم | شركة البركة - تغطية كاملة",
    metaDescription: "شركة البركة لنقل الأثاث في منطقة الهرم. تغطية كاملة لجميع أحياء الهرم بفرق متخصصة.",
    description: "تغطية كاملة لجميع أحياء ومناطق الهرم.",
    neighborhoods: ["شارع الهرم", "المريوطية", "البراجيل", "كرداسة", "أبو النمرس"],
  },
  {
    slug: "mohandessin",
    name: "المهندسين",
    group: "giza",
    metaTitle: "نقل أثاث المهندسين | شركة البركة - خدمة راقية",
    metaDescription: "شركة البركة لنقل الأثاث في المهندسين. متخصصون في شقق وفلل المهندسين الفاخرة، خدمة احترافية.",
    description: "خبرة في نقل الأثاث الفاخر في المهندسين.",
    neighborhoods: ["شارع جامعة الدول", "شارع لبنان", "ميدان المهندسين", "الدقي"],
  },
  {
    slug: "dokki",
    name: "الدقي",
    group: "giza",
    metaTitle: "نقل أثاث الدقي | شركة البركة - فرق متخصصة",
    metaDescription: "شركة البركة لنقل الأثاث في الدقي. خدمة احترافية بفرق مدربة وسيارات مجهزة.",
    description: "نقل أثاث احترافي في الدقي وما حولها.",
    neighborhoods: ["شارع التحرير", "ميدان الدقي", "الجيزة", "أورمان"],
  },
  {
    slug: "agouza",
    name: "العجوزة",
    group: "giza",
    metaTitle: "نقل أثاث العجوزة | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في العجوزة. فرق مدربة وخدمة سريعة بأسعار مناسبة.",
    description: "نقل أثاث سريع واحترافي في العجوزة.",
    neighborhoods: ["شارع النيل", "ميدان العجوزة", "كورنيش النيل"],
  },
  {
    slug: "imbaba",
    name: "إمبابة",
    group: "giza",
    metaTitle: "نقل أثاث إمبابة | شركة البركة - أسعار مناسبة",
    metaDescription: "شركة البركة لنقل الأثاث في إمبابة. خدمة احترافية بأسعار مناسبة وفرق مدربة.",
    description: "نقل أثاث إمبابة وما حولها بأسعار مناسبة.",
    neighborhoods: ["إمبابة القديمة", "الوراق", "أوسيم"],
  },

  // ========== المدن الجديدة (VIP) ==========
  {
    slug: "sheikh-zayed",
    name: "الشيخ زايد",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث الشيخ زايد | شركة البركة - خدمة VIP فاخرة",
    metaDescription: "شركة البركة لنقل الأثاث في الشيخ زايد. خدمة احترافية للفلل والكمبوندات، فرق متخصصة في الأثاث الفاخر.",
    description: "متخصصون في خدمة كمبوندات وفلل الشيخ زايد الفاخرة بأعلى معايير الاحترافية.",
    compounds: ["Beverly Hills", "Allegria", "Westown Residence", "Zed Towers", "Etapa", "The Estates", "Royal City", "Palm Hills Zayed"],
    neighborhoods: ["الحي الأول", "الحي الثاني", "الحي الثالث", "الثامن من مايو"],
  },
  {
    slug: "6-october",
    name: "6 أكتوبر",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث 6 أكتوبر | شركة البركة - تغطية كاملة",
    metaDescription: "شركة البركة لنقل الأثاث في 6 أكتوبر. خدمة احترافية في جميع أحياء وكمبوندات 6 أكتوبر.",
    description: "تغطية شاملة لجميع أحياء وكمبوندات مدينة 6 أكتوبر.",
    compounds: ["Palm Hills October", "Mountain View iCity October", "O West", "Badya", "New Giza", "Uptown October", "Sodic West"],
    neighborhoods: ["الحي الأول", "الحي الثالث", "الحي السادس", "الحي الحادي عشر", "المحور المركزي"],
  },
  {
    slug: "october-gardens",
    name: "حدائق أكتوبر",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث حدائق أكتوبر | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في حدائق أكتوبر. فرق متخصصة وتغليف احترافي.",
    description: "نقل أثاث احترافي في حدائق أكتوبر وما حولها.",
    compounds: ["Hadayek October Villas", "Green 5 October"],
    neighborhoods: ["المنطقة الأولى", "المنطقة الثانية", "المنطقة الثالثة"],
  },
  {
    slug: "tagamoa-khames",
    name: "التجمع الخامس",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث التجمع الخامس | شركة البركة - خدمة راقية",
    metaDescription: "شركة البركة لنقل الأثاث في التجمع الخامس. متخصصون في كمبوندات التجمع الفاخرة.",
    description: "متخصصون في نقل الأثاث الفاخر داخل كمبوندات التجمع الخامس.",
    compounds: ["Mivida", "Villette", "Hyde Park", "Village Gardens Katameya", "Palm Hills New Cairo", "Eastown", "Stone Residence", "Lake View Residence"],
    neighborhoods: ["التجمع الأول", "التجمع الثالث", "المنطقة المركزية", "النرجس", "البنفسج", "القرنفل"],
  },
  {
    slug: "new-cairo",
    name: "القاهرة الجديدة",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث القاهرة الجديدة | شركة البركة - خدمة VIP",
    metaDescription: "شركة البركة لنقل الأثاث في القاهرة الجديدة. متخصصون في الكمبوندات والفلل.",
    description: "خبرة واسعة في نقل الأثاث داخل كمبوندات القاهرة الجديدة الفاخرة.",
    compounds: ["Mountain View 1", "Mountain View 2", "Sarai", "Taj City", "Waterway"],
    neighborhoods: ["التجمع الأول", "التجمع الثاني", "المعراج", "اللوتس", "الياسمين"],
  },
  {
    slug: "madinaty",
    name: "مدينتي",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث مدينتي | شركة البركة - خبراء المدن الجديدة",
    metaDescription: "شركة البركة لنقل الأثاث في مدينتي. خبرة في كمبوندات مدينتي، فرق متخصصة وتغليف احترافي.",
    description: "خبرة متميزة في نقل الأثاث داخل مجتمع مدينتي السكني المتكامل.",
    compounds: ["Madinaty Villas", "Madinaty Apartments", "Madinaty B1", "Madinaty B2"],
    neighborhoods: ["الحرف A", "الحرف B", "الحرف C", "الحرف G", "المنطقة التجارية"],
  },
  {
    slug: "rehab",
    name: "الرحاب",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث الرحاب | شركة البركة - خبراء المنطقة",
    metaDescription: "شركة البركة لنقل الأثاث في الرحاب. خبرة في جميع مراحل الرحاب وتغليف احترافي.",
    description: "خبرة عميقة في نقل الأثاث داخل مدينة الرحاب بجميع مراحلها.",
    compounds: ["Rehab 1", "Rehab 2", "Rehab City"],
    neighborhoods: ["المرحلة الأولى", "المرحلة الثانية", "المرحلة الثالثة", "المرحلة الرابعة"],
  },
  {
    slug: "shorouk",
    name: "مدينة الشروق",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث مدينة الشروق | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في مدينة الشروق. فرق مدربة وسيارات مجهزة وأسعار مناسبة.",
    description: "نقل أثاث احترافي في جميع أحياء مدينة الشروق.",
    neighborhoods: ["الحي الأول", "الحي الثاني", "الحي الثالث", "حي الأندلس"],
  },
  {
    slug: "new-capital",
    name: "العاصمة الإدارية",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث العاصمة الإدارية | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث للعاصمة الإدارية الجديدة. خبراء في النقل للمدن الجديدة.",
    description: "متخصصون في نقل الأثاث للعاصمة الإدارية الجديدة من جميع مناطق القاهرة.",
    compounds: ["Midtown Condo", "IL Bosco", "Haptown", "Taj Tower", "Scenario"],
    neighborhoods: ["الحي السكني R1", "الحي السكني R2", "الحي السكني R3", "الحي الحكومي"],
  },
  {
    slug: "mostakbal-city",
    name: "مدينة المستقبل",
    group: "new-cities",
    isVip: true,
    metaTitle: "نقل أثاث مدينة المستقبل | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في مدينة المستقبل. خبراء في الكمبوندات الجديدة.",
    description: "نقل أثاث احترافي في كمبوندات مدينة المستقبل الحديثة.",
    compounds: ["Aria", "Bloom Fields", "La Verde", "Aliva", "Creek Town"],
    neighborhoods: ["المنطقة الأولى", "المنطقة الثانية"],
  },
  {
    slug: "badr-city",
    name: "مدينة بدر",
    group: "new-cities",
    isVip: false,
    metaTitle: "نقل أثاث مدينة بدر | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في مدينة بدر. فرق متخصصة ومدربة وأسعار منافسة.",
    description: "نقل أثاث احترافي في مدينة بدر بفرق متخصصة.",
    neighborhoods: ["الحي الأول", "الحي الثاني", "الحي الثالث", "المنطقة الصناعية"],
  },
  {
    slug: "obour",
    name: "مدينة العبور",
    group: "new-cities",
    isVip: false,
    metaTitle: "نقل أثاث مدينة العبور | شركة البركة",
    metaDescription: "شركة البركة لنقل الأثاث في مدينة العبور. خدمة شاملة تشمل الفك والتركيب والتغليف.",
    description: "نقل أثاث متكامل في مدينة العبور.",
    neighborhoods: ["الحي الأول", "الحي الثاني", "الحي الثالث", "الحي السابع"],
  },
];

// مجموعات المناطق
export const areaGroups = {
  cairo: {
    label: "القاهرة",
    areas: areas.filter((a) => a.group === "cairo"),
  },
  giza: {
    label: "الجيزة",
    areas: areas.filter((a) => a.group === "giza"),
  },
  "new-cities": {
    label: "المدن الجديدة",
    areas: areas.filter((a) => a.group === "new-cities"),
  },
};

// المناطق VIP فقط
export const vipAreas = areas.filter((a) => a.isVip);

// المناطق المميزة في الصفحة الرئيسية
export const featuredAreas = [
  "sheikh-zayed",
  "tagamoa-khames",
  "madinaty",
  "6-october",
  "new-capital",
  "new-cairo",
];
